# Makefile para automatizar la generación de circuitos para informes

FIG_DIR = ../Informe/Figuras

# Copia las figuras generadas por XCircuit (no sería necesario porque
# latex accede a la carpeta XCircuit por sí solo

all:
	cp *.eps $(FIG_DIR)
	cp *.tex $(FIG_DIR) 

clean:
	-rm -f *eps-converted-to.pdf
